### ISSUE TITLE
use dask arrays

### ISSUE THREAD

**Issue by larsbuntemeyer** [euro-cordex/cordex-sce#1]
# dask optimization

Instead of explicitly parallelizing with MPI, the processing seems to be a good use case for [dask](https://jobqueue.dask.org/en/latest/).

**Comment by RussellGl** [comment]
Just saw this... 
Haven't heard of dask before, but I can look into it.

**Comment by larsbuntemeyer** [comment]
Yes, i wanted to try that on our jupyterhub at DKRZ. It seems to be much easier than explicitly using MPI! I just put that issue here to remember it.
